src/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PostPathController.cls
public class PostPathController {
 @AuraEnabled
 public static List < String > getPostStatus() {  
  List < String > status = new list < String > ();    
  //Get object info 
  Schema.DescribeSObjectResult ObjInfo = Schema.Post__c.getSObjectType().getDescribe(); 
  // Get a map of fields for the SObject
  map < String, Schema.SObjectField > fieldMap = ObjInfo.fields.getMap(); 
  // Get the list of picklist values for this field.
  list < Schema.PicklistEntry > values = fieldMap.get('Status__c').getDescribe().getPickListValues(); 
  // Add these values to the selectoption list.
  for (Schema.PicklistEntry a: values) {
   status.add(a.getValue());
  }
  system.debug('allOpts ---->' + status);
  status.sort();     
  return status;
 }
}