src/objects/Post__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Published</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Under Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Post</label>
    <nameField>
        <label>Post Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Posts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApprovalProcessTest.cls
@isTest
public class ApprovalProcessTest {
	
    Static testMethod void sendForApproveTest(){
        Post__c p = new Post__c();
        p.Name = 'Post name 678';
        insert p;
        Test.startTest();
        p.Status__c = 'Under Review';
        update p;
        List<ProcessInstance> processInstances = [select Id, Status from ProcessInstance where TargetObjectId = :p.id];
        System.assertEquals(processInstances.size(),1);       
        Test.stopTest();  
    }
        
        
        
}